
// 课程包状态
const PACKAGE_STATE_UNAUDIT = 0;   // 未审核
const PACKAGE_STATE_AUDITING = 1;  // 审核中
const PACKAGE_STATE_AUDIT_SUCCESS = 2; // 审核成功
const PACKAGE_STATE_AUDIT_FAILED = 3;  // 审核失败

module.exports = {
	PACKAGE_STATE_UNAUDIT,
	PACKAGE_STATE_AUDITING,
	PACKAGE_STATE_AUDIT_SUCCESS,
	PACKAGE_STATE_AUDIT_FAILED
};
